version: '3.3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data_dev:/var/opt/mssql

  frontend:
    image: frontend:dev
    build:
      context: ../../Frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - notification-service
      - transaction-service

  user-service:
    image: user-service:dev
    build:
      context: ../../Backend/UserService/UserService
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=AppDb;User=sa;Password=${MSSQL_PASSWORD}
    depends_on:
      - mssql

  notification-service:
    image: notification-service:dev
    build:
      context: ../../Backend/NotificationService/NotificationService
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=AppDb;User=sa;Password=${MSSQL_PASSWORD}
    depends_on:
      - mssql

  transaction-service:
    image: transaction-service:dev
    build:
      context: ../../Backend/TransactionService/Transaction Service
    ports:
      - "5003:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=AppDb;User=sa;Password=${MSSQL_PASSWORD}
    depends_on:
      - mssql

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  mssql_data_dev:
